language: python

sudo: true
fast_finish: true

python:
  # - "3.5"
  - "3.6"

before_install:
#   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#   - sudo apt-get update -qq
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install g++-4.8 libsnappy-dev zlib1g-dev libbz2-dev cmake-data cmake -qq
 - export CXX="g++-4.8" CC="gcc-4.8"

install:
  # - sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev
  # - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  # # - sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev
  # # - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  # # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - pip install snappy
  - pip install Cython
  - pip install -r requirements.txt
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
